# Generated by Django 2.1.1 on 2019-02-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190211_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.TextField(default='first'),
            preserve_default=False,
        ),
    ]
