# Generated by Django 2.1.1 on 2019-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
    ]
