# Generated by Django 2.1.1 on 2019-02-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_restaurant_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
