# Generated by Django 2.1.1 on 2019-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
