# Generated by Django 2.1.1 on 2019-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_imagedish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishreview',
            name='stars',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='stars',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
